Producer:
  task_start:
    name: "任务开始"
    command: "python {mira_dir}/miraPipeline/pipeline/task_start/task_start.py"
    order: 1
  task_publish:
    name: "任务入库"
    command: "python {mira_dir}/miraPipeline/pipeline/task_publish/task_publish.py"
    order: 2
  export_fbx_camera:
    name: "导出fbx摄像机"
    command: "python {mira_dir}/miraPipeline/maya/export_fbx_camera/export_fbx_camera.py"
    order: 3

TD:
  task_start:
    name: "任务开始"
    command: "python {mira_dir}/miraPipeline/pipeline/task_start/task_start.py"
    order: 1
  task_publish:
    name: "任务入库"
    command: "python {mira_dir}/miraPipeline/pipeline/task_publish/task_publish.py"
    order: 2
  export_fbx_camera:
    name: "导出fbx摄像机"
    command: "python {mira_dir}/miraPipeline/maya/export_fbx_camera/export_fbx_camera.py"
    order: 3